service: my-express-application

provider:
  name: aws
  runtime: nodejs16.x
  region: us-east-1

plugins:
  - serverless-bundle
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 4000

functions:
  app:
    handler: src/handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: "*"

package:
  individually: true
